### PR TITLE
Fix CSRF in task comments / descriptions

### PR DESCRIPTION
**Pull request by multun**
You can verify this issue actually exists by creating an issue or comment containing:

```
<script>alert("oh noez");</script>
```

### CODE REVIEW

**Comment by shacker** [comment]
This is not related to CSRF in any way, but it is a failure to sanitize inbound content. Thanks for finding this - it is indeed a regression from todo 1.x to todo 2.x ! 

I've fixed it in f526ed51665a9955a7dac26878b16d07e7aeb758 , added test, and bumped the version. Thanks again for catching this!

**Comment by multun** [comment]
Fair enough, thanks for the fix !

**Comment by multun** [comment]
> but it is a failure to sanitize inbound content

@shacker so users are supposed to be able to write html code in their comments ? why not choosing a more readable option, such as markdown ?

**Comment by shacker** [comment]
@multun Yeah this is a tough one to get right for all possible implementations. I can imagine some sites wanting markdown, others limited HTML with GUI editors. Just double-checked - this does not strip markdown, so it'll work for either (though the markdown is displayed un-parsed). For now, most important to fix the security hole.

**Pull request closed without merging**
