### PR TITLE
Add basis for automated tests and QA

### PR DESCRIPTION
**Pull request by bittner**
* Add tox configuration and integration with setup.py
* Add Travis CI build server configuration
* Add badges and Tests section to README
* Bump version (development)
* Fix flake8 complaints
* Move flake8 configuration into tox config file
* Add long_description and custom clean command (setup.py)

### CODE REVIEW

**Comment by bittner** [comment]
@shacker When this is merged you'll have to create a personal account on both [Travis CI](https://travis-ci.org/shacker/django-todo) and [Landscape](https://landscape.io/github/shacker/django-todo/master) to make the badges in the README work as expected. When you use your GitHub user name for both the badges will work right away.

**Comment by bittner** [comment]
I've added issue #28, because it felt bad to increase the `max-complexity` setting of `flake8`. This way this sin will not be forgotten so easily I thought.

**Comment by shacker** [comment]
This is a huge step forward. Thanks Peter for your substantial contributions!

**Comment by bittner** [comment]
Maybe you have a small demo project (the one that you use to test the app, maybe?) that you could add to the repository? If you would note down the steps you perform in your manual tests, say, in a issue on GitHub we could implement automated BDD tests using [behave-django](https://github.com/behave/behave-django).

**Comment by bittner** [comment]
Please don't forget to activate your repo [on Travis CI](https://travis-ci.org/shacker/django-todo). Probably you still need to give Travis access to your GitHub account and select the repo, or so. The [.travis.yml](https://github.com/shacker/django-todo/blob/master/.travis.yml) file is already in place. See the [Getting Started guide](https://travis-ci.org/getting_started) for help.

[Landscape](https://landscape.io/github/shacker/django-todo/master) is always a bit unstable, [down regularly](https://github.com/landscapeio/landscape-issues/issues/179), don't worry. You can usually spot this from the [broken badge](https://github.com/landscapeio/landscape-issues/issues/178). But it's free, and it's a good thing when it's working!

Please watch out to really give those services the permissions they need to access the repo! GitHub has introduced a few awesome security features half a year ago (or so) that regularly cause pain.

**Pull request merged**
